In [1]:
# Class: CS460G - Machine Learning
# Project: Assignmnet 4 - Linear Classifiers / Variance-Bias / Kernels
# Question: 1
# Author: Sydney Chapman 
# Date: 10/20/2023


import sklearn as sk
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
ds1 = pd.read_csv("top_critic_reviews.csv", sep=",", names = ["review_score","review_content"])

display(ds1)

        review_score                                     review_content
0       review_score                                     review_content
1                NaN  What's really lacking in The Lightning Thief i...
2                NaN  It's more a list of ingredients than a movie-m...
3              3.5/5  Percy Jackson isn't a great movie, but it's a ...
4                3/5  Crammed with dragons, set-destroying fights an...
...              ...                                                ...
288532           NaN  Zulu is a fairly tough-minded and interesting ...
288533           NaN  Joseph E. Levine makes an impressive debut in ...
288534           NaN  This may not be exact history, but it certainl...
288535            B+  A brilliantly made dramatisation of Rorke's Dr...
288536           NaN  It may not be truthful - but, my God, the resu...

[288537 rows x 2 columns]

In [3]:
ds1.dropna(subset=["review_score"], inplace=True);
display(ds1);

        review_score                                     review_content
0       review_score                                     review_content
3              3.5/5  Percy Jackson isn't a great movie, but it's a ...
4                3/5  Crammed with dragons, set-destroying fights an...
5                2/4  For what it is and for whom it is intended, it...
6                2/5  Chris Columbus returns to his comfort zone for...
...              ...                                                ...
288527           4/5  One of the film's great strengths is the trust...
288528           4/5  The film feels like a riposte to Trump-ism. It...
288529           4/5  The genius of the film lies in its combination...
288531         2.5/4  Students of such things in movies should appre...
288535            B+  A brilliantly made dramatisation of Rorke's Dr...

[186018 rows x 2 columns]

In [5]:
ds1.dropna(subset=["review_content"], inplace=True);
display(ds1);

print(ds1.shape)

        review_score                                     review_content
0       review_score                                     review_content
3              3.5/5  Percy Jackson isn't a great movie, but it's a ...
4                3/5  Crammed with dragons, set-destroying fights an...
5                2/4  For what it is and for whom it is intended, it...
6                2/5  Chris Columbus returns to his comfort zone for...
...              ...                                                ...
288527           4/5  One of the film's great strengths is the trust...
288528           4/5  The film feels like a riposte to Trump-ism. It...
288529           4/5  The genius of the film lies in its combination...
288531         2.5/4  Students of such things in movies should appre...
288535            B+  A brilliantly made dramatisation of Rorke's Dr...

[178138 rows x 2 columns]

(178138, 2)

In [7]:
ds1.to_csv("top_critic_reviews.csv", sep=",", index=False, encoding='utf-8')

In [21]:
ds2 = pd.read_csv("top_critic_reviews.csv", sep=",", names = ["review_score","review_content"])

display(ds2)

        review_score                                     review_content
0       review_score                                     review_content
1              3.5/5  Percy Jackson isn't a great movie, but it's a ...
2                3/5  Crammed with dragons, set-destroying fights an...
3                2/4  For what it is and for whom it is intended, it...
4                2/5  Chris Columbus returns to his comfort zone for...
...              ...                                                ...
178133           4/5  One of the film's great strengths is the trust...
178134           4/5  The film feels like a riposte to Trump-ism. It...
178135           4/5  The genius of the film lies in its combination...
178136         2.5/4  Students of such things in movies should appre...
178137            B+  A brilliantly made dramatisation of Rorke's Dr...

[178138 rows x 2 columns]

In [32]:
print(ds2['review_score'][1][0])

ds2.drop(ds2[ds2['review_score'].str.contains("C")].index, inplace=True)
ds2.drop(ds2[ds2['review_score'].str.contains("B")].index, inplace=True)
ds2.drop(ds2[ds2['review_score'].str.contains("A")].index, inplace=True)
ds2.drop(ds2[ds2['review_score'].str.contains("D")].index, inplace=True)
ds2.drop(ds2[ds2['review_score'].str.contains("F")].index, inplace=True)

print(ds2)

3
        review_score                                     review_content
0       review_score                                     review_content
1              3.5/5  Percy Jackson isn't a great movie, but it's a ...
2                3/5  Crammed with dragons, set-destroying fights an...
3                2/4  For what it is and for whom it is intended, it...
4                2/5  Chris Columbus returns to his comfort zone for...
...              ...                                                ...
178132           4/5  There's a magical moment in every movie of qua...
178133           4/5  One of the film's great strengths is the trust...
178134           4/5  The film feels like a riposte to Trump-ism. It...
178135           4/5  The genius of the film lies in its combination...
178136         2.5/4  Students of such things in movies should appre...

[152305 rows x 2 columns]

In [33]:
ds2.to_csv("cleaned_reviews.csv", sep=",", index=False, encoding='utf-8')

In [ ]:
# Dataset that includes the movie titles 
ds3 = pd.read_csv("rotten_tomatoes_movies.csv", sep=",", header=0)

display(ds3)

In [ ]:
cleaned_ds3 = ds3[['movie_title']].copy()

display(cleaned_ds3)

In [ ]:
cleaned_ds3.to_csv("movie_titles.csv", sep=",", index=False, encoding='utf-8')